source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'FastImageCache', '~> 1.3'
pod 'UIImage-Categories', '~> 0.0.1'
#pod 'mage-ios-sdk', :git => 'git@git.***REMOVED***:mage/mage-ios-sdk', :tag => '0.0.2'
pod 'mage-ios-sdk', :path => '../mage-ios-sdk'
