platform :ios, '7.0'
pod 'JVFloatLabeledTextField',	'~> 0.0.5'
pod 'RESideMenu', '~> 4.0.3'
pod 'DateTools', '~> 1.3.0'
pod 'objective-zip', '~> 0.8.3'
#pod 'mage-ios-sdk', :git => 'git@git.***REMOVED***:mage/mage-ios-sdk', :tag => '0.0.2'
pod 'mage-ios-sdk', :path => '/data/git/mage-ios-sdk'
