name: Release

on: 
  release:
    types: [published]
jobs:
  build:
   runs-on: macos-latest

   steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: mage-ios
    - name: Clone MAGE SDK
      uses: actions/checkout@master
      with:
        repository: ngageoint/mage-ios-sdk
        path: 'mage-ios-sdk'
        fetch-depth: 0
    - name: Install Utilities
      run: |
        brew install automake
        brew install libtool
    - name: Install Dependencies
      run: |
        gem install xcodeproj
      working-directory: mage-ios
    - name: Configure Signing Certificate and Provisioning Profiles
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.CERTIFICATE_PASSPHRASE }}" --output development.p12 ./.github/secrets/development.p12.gpg
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.PROFILE_PASSPHRASE }}" --output MAGE.mobileprovision ./.github/secrets/MAGE.mobileprovision.gpg
      working-directory: mage-ios
    - name: Checkout Application Branch
      run: git checkout ${{ github.event.inputs.appBranch }}
      working-directory: mage-ios
    - name: Install Pods
      run: |
        pod repo update
        pod install
      working-directory: mage-ios
    - name: Build
      env: 
        KEYCHAIN_NAME: "${{ secrets.KEYCHAIN_NAME }}"
        KEYCHAIN_PASSWORD: "${{ secrets.KEYCHAIN_PASSWORD }}"
        CERTIFICATE_PASSWORD: "${{ secrets.CERTIFICATE_PASSWORD }}"
      run: |
        fastlane build
      working-directory: mage-ios
    - name: Bundle Artifacts
      run: |
         tar -czvf MAGE.xcarchive.tar.gz MAGE.xcarchive/
      working-directory: mage-ios/build
    - name: Get Upload URL
      id: url
      run:   |
        url="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${GITHUB_REF#refs/tags/}"
        echo ::set-output name=upload_url::$(curl -sL $url | jq -r '.upload_url')
    - name: Upload Artifacts
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.url.outputs.upload_url }}
        asset_path: mage-ios/build/MAGE.xcarchive.tar.gz
        asset_name: MAGE.xcarchive.tar.gz
        asset_content_type: application/octet-stream